### PR TITLE
update ruRU localization

### PR DESCRIPTION
**Pull request by Artur91425**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Thinks like `L.TANK_ICON             = "|TInterface\\AddOns\\DBM-Core\\textures\\UI-EJ-Icons.blp:20:20:0:0:255:66:6:21:7:27|t"` don't actually need to be added, because you're just replacing a string with an identicle string. Only need to add it if it's being changed.

**Comment by Artur91425** [comment]
Terribly! I had to analyze `Localization.en.lua` a few hours to bring `Localization.ru.lua` to `Localization.en.lua` state. Otherwise it was impossible to understand what lines is missing, which are already outdated. Honestly, I do not understand how this situation turned out. Are you when you make any changes to `Localization.en.lua` do not update the files of other localizations? If so, then this is a very strange approach.

**Comment by Artur91425** [comment]
> Thinks like L.TANK_ICON = "|TInterface\\AddOns\\DBM-Core\\textures\\UI-EJ-Icons.blp:20:20:0:0:255:66:6:21:7:27|t" don't actually need to be added, because you're just replacing a string with an identicle string. Only need to add it if it's being changed.
I understand that I rewrite the same line, however, I did it specifically that the file Localization.ru.lua was completely identical to Localization.en.lua. And this is necessary that in the future it is confident that localization files are the same and do not have to analyze their several hours looking for the missing lines. How it had to do to me.

**Comment by MysticalOS** [comment]
> Terribly! I had to analyze `Localization.en.lua` a few hours to bring `Localization.ru.lua` to `Localization.en.lua` state. Otherwise it was impossible to understand what lines is missing, which are already outdated. Honestly, I do not understand how this situation turned out. Are you when you make any changes to `Localization.en.lua` do not update the files of other localizations? If so, then this is a very strange approach.

The way it works is english is loaded first, then other languages are imported over it replacing strings, this way if any strings re missing from say ru, the english ones still exist there. but if no replacements needed no need to add outsidse english

as for system, you were offered an alternative one that's probably 10x easier but you have to hop into the discord and reach out to qartemist

**Review by QartemisT — APPROVED** [review]

**Comment by QartemisT** [comment]
Resolved the build errors, resynced with master, and whatnot.

I appreciate the PR @Artur91425 :)
Future cases, do reach out to us about using the translation portal we have, which makes updating these much faster.

**Pull request merged**
