### PR TITLE
Update Kel'Thuzad.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**
Gluth Frenzy
https://cn.classic.warcraftlogs.com/reports/na261Gg94W8tmHJP#fight=59&type=dispels&ability=28371

Kel'Thuzad 
https://cn.classic.warcraftlogs.com/reports/JWLyRAngfM9xK8Tm#fight=last&type=auras&spells=debuffs

### CODE REVIEW

**Comment by QartemisT** [comment]
@nanjuekaien1 Wat is this PR meant to mean exactly?

**Comment by nanjuekaien1** [comment]
Kel'Thuzad
mod:AddSetIconOption("SetIconOnFrostTomb", 28169, true, false, {1, 2, 3, 4, 5, 6, 7, 8}) --28169 the spell  is Grobbulus

**Comment by MysticalOS** [comment]
This should have been a ticket, not a PR. I can see problem with icon option spellId, but what's wrong with frenzy?

**Comment by nanjuekaien1** [comment]
Can frenzy's alert be added?

**Pull request closed without merging**
