### PR TITLE
Update localization.ru.lua

### PR DESCRIPTION
**Pull request by Molkree**
Wave1 string actually changes with gender, it ends with "девушка" for females and "юноша" for males.

### CODE REVIEW

**Comment by MysticalOS** [comment]
In this particular case, it may be better to use partial string, since mod checks for match or partial match. include enough string that's common in both.

**Comment by anon1231823** [comment]
@Molkree I don't know if you know @jekalich but can you go through the modules and update the missing strings in russian? BWL, Azeroth, Dungeons, etc. have some missing stuff. Look at the english localization file to check for any missing strings.

**Comment by Molkree** [comment]
@anon1231823, nope, I do not know @JekaLich :)
And yes, I can look in other places, there's only one issue, my max level character is only level 90 on Russian servers so I won't be able to do anything in Azeroth or other recent expansions (I don't plan to play on Russian servers).
Another question, do you know if localizations are the same in Classic and Retail? I assumed so but not sure now.

**Comment by MysticalOS** [comment]
Some are same, some are not. usually boss name corrections, typo corrections on retail that aren't in classic.

**Pull request merged**
