### PR TITLE
aq/visc: add a bossvisible call if all globs are dead

### PR DESCRIPTION
**Pull request by venuatu**
my raid had this but there were only 19 unit_deads, instead of the expected 20

### CODE REVIEW

**Comment by MysticalOS** [comment]
I feel like this would cause accuracy problems if it's not actually visible yet. boss visible itself should be improved to scan targets of all raid members and require boss to be targetted to return true in this check at very least. in a 40 man raid, at least someone is gonna target boss pretty fast, after all,can't get frost hits if no one is targetting boss.

**Comment by MysticalOS** [comment]
Another bugs I see
It never resets mod.vb.globsDead which means if you don't one phase boss it'll literally call boss visible instantly on first blob death of second blog phase.

**Comment by venuatu** [comment]
You only get one glob spawn per 5% of boss health left at the shatter
Then every glob you kill takes 5% health away from the boss
There should only be 19 total glob kills per encounter, as the boss dies if you shatter under 5%

**Comment by MysticalOS** [comment]
This feature is no longer being supported, closing PR

**Pull request closed without merging**
