### PR TITLE
naxx/loatheb: healer corrupted mind tracker

### PR DESCRIPTION
**Pull request by venuatu**

### CODE REVIEW

**Review by MysticalOS — CHANGES_REQUESTED** [review]
Don't use `for i = 1, 40 do`

check actual number of group members in group and inside the raid.

**Comment by venuatu** [comment]
@MysticalOS is `GetNumSubgroupMembers() + 1` the right thing instead of 40?

**Comment by MysticalOS** [comment]
No, that'd return 5. Should use DBms function that auto chooses right iterator Most functions do

This

https://github.com/DeadlyBossMods/DeadlyBossMods/blob/master/DBM-CastleNathria/HungeringDestroyer.lua#L119

**Comment by venuatu** [comment]
I'm not too worried about people outside, classic raids are usually always at the 40 cap with everyone inside
plus missing healers can really hurt on this boss

**Comment by MysticalOS** [comment]
Mods should always consider future proofing. people will be running nax well into TBC for staff, like they did in original TBC. Such features may also be ported back to retail mods as well, which are even more unpredictable. 

if you don't do it though no worries I'll probably add it later either way.

**Comment by venuatu** [comment]
@QartemisT it broke, missed some brackets, will upload later
```
				addLine(tostring(cid) .. '*' .. mobNames[cid] or name, tostring(mobCounts[cid]))
```
should be
```
				addLine(tostring(cid) .. '*' .. (mobNames[cid] or name), tostring(mobCounts[cid]))
```

1x DBM-Naxx\MilitaryQuarter\Gothik.lua:69: attempt to concatenate field '?' (a nil value)

**Comment by venuatu** [comment]
looked good
loath-mind

**Comment by MysticalOS** [comment]
Do you think it's better to alpha sort vs numeric sort?

**Comment by venuatu** [comment]
my raid does alphabetical order, I guess it could be by duration and then by name, which would remove that switch

**Review by MysticalOS — APPROVED** [review]

**Comment by MysticalOS** [comment]
I hadn't noticed it aleady has a switch, that's good enough for me, merged

**Pull request merged**
