### PR TITLE
Update localization.cn.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Approving, but might want to localize the other tentacle timers/warnings as well if not already done.

**Comment by nanjuekaien1** [comment]
@MysticalOS  Tentacle timers/warnings have been perfected, and the follow-up will come from Cyanokaze. I found people:)

**Comment by MysticalOS** [comment]
Much appreciated @nanjuekaien1

**Comment by nanjuekaien1** [comment]
@MysticalOS  Want to know how the blood volume of the stomach tentacles is displayed in the second stage of CThun?

**Pull request merged**
