### PR TITLE
aq/trash: add warning for cause insanity / mind control

### PR DESCRIPTION
**Pull request by venuatu**
#332

### CODE REVIEW

**Comment by MysticalOS** [comment]
Does this only affect one target out of 40? if it can affect multiple targets it should be an aggregated warning (combinedShow within 0.3 sec)

**Comment by venuatu** [comment]
@MysticalOS one per mob, though there could be up to 5 of them in a pack if your unlucky

**Comment by MysticalOS** [comment]
multi mob in one pack something should be adjusted for to reduce spam. and because it's multi mob, I'd switch aggregation to 0.75 or 1 even. just to make sure if 5 mobs cast it at same time, or at least within 1 second, it's combined into single warning.

**Comment by venuatu** [comment]
Switched over to combined show with 0.75
If it happens on a tank it could be bad depending on group, so don't want to delay it too much

**Pull request merged**
