### PR TITLE
Update RaidWarningSpecial.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**
SpecialWarnSoundOption  overlapping ，Adjusted

### CODE REVIEW

**Comment by QartemisT** [comment]
Could you screenshot how this is overlapping? We tested this several times with no issues.

**Comment by nanjuekaien1** [comment]
重叠

**Comment by QartemisT** [comment]
I'll investigate shortly :)

**Comment by nanjuekaien1** [comment]
申请0
Can you widen these boxes to display 1 to 2 bytes?

**Comment by QartemisT** [comment]
We can probably do that also :) I'm doing a lot of GUI updates this week especially involving options etc. Going to close this PR as both these issues are on my list

p.s. You should consider joining the discord :)

**Comment by nanjuekaien1** [comment]
@QartemisT 
Thanks, I won't program, I can help localize the zhCN file at most  :)

**Pull request closed without merging**
