### PR TITLE
Update localization.es.lua

### PR DESCRIPTION
**Pull request by woopydalan**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Already see the typo
DBM_CORE_AUTO_ANNOUNCE_OPTIONScountdown
should be
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.countdown

**Comment by woopydalan** [comment]
How do I edit this commit ??

**Comment by MysticalOS** [comment]
if you commit to that branch again, it's automatically updated in the PR so you just fix it, and commit fix.

**Comment by woopydalan** [comment]
Why did it fail again?

**Comment by MysticalOS** [comment]
Oh, the , at the end doesn't belong either. Sorry missed that too.

**Pull request merged**
