### PR TITLE
Update Razorgore.lua

### PR DESCRIPTION
**Pull request by Bisonpasfute**
Better way to count the number of destroyed eggs

### CODE REVIEW

**Comment by QartemisT** [comment]
This won't work effectively, because of the combat log range, and would no doubt require a lot more people in the raid to be running DBM to sync correctly.
Though best to get @MysticalOS's view on this.

**Comment by MysticalOS** [comment]
Yes that was reason this was disabled. Combat log range, and even when trying to do syncing, it was wonky because in a raid of 40 people it only takes ONE person who's lagging to send some bad egg reports.

I even remember looking at this method on warcraft logs and found WILD inconsistencies with number of casts vs number of eggs. I think it's possible to cast destroy egg for example but not being in range of any eggs for example.

That said the yell method is also very inaccurate because it's based on a pretty false assumption. I'm pretty sure it's not every 2 eggs for every year like that contributor thought. Instead. he DOES yell for every egg, BUT it has an ICD so he usually skips every other yell. However if person is slow, it's possible for only one egg to be destroyed between yells instead of 2 or if person is really fast, maybe even possible for 3 eggs between yells which is why that method kinda lines up within 2 eggs but rarely lines up perfectly.

My stance on it though is unless blizzard reverts nerf to combat log range, i'll either leave it as is, or remove it completely.

**Comment by Bisonpasfute** [comment]
Thanks for the answers guys. I thought that because SPELL_CAST_SUCCESS was used for another spell that it'd legitimate the use I did but that's alright. And yeah, for the yells, I tested the actual code a bit and sometimes it yells at the first egg and thus count 2 instead of one, and sometimes no. Also, on the tests I did it was every two eggs for sure that the boss was yelling. I could more testing if u'd like. And just for my knowledge, why would it break the volley warnings in stage 2 ?

**Comment by MysticalOS** [comment]
"And just for my knowledge, why would it break the volley warnings in stage 2"
Because you changed it from using spell NAME to spellId, as i said above, they disabled addons using spellIds in classic. All spellids return 0 in game, so that statement would NEVER be true.
Also I meant the stage 2 detection cast not the volley my bad.

**Pull request closed without merging**
