### PR TITLE
aq/fankriss: add entangle warning and yell

### PR DESCRIPTION
**Pull request by venuatu**
#332

### CODE REVIEW

**Comment by venuatu** [comment]
@QartemisT is it ok to register SPELL_AURA_APPLIED in both RegisterEventsInCombat and RegisterShortTermEvents?

**Comment by MysticalOS** [comment]
no, that'd make it registered twice. If it needs to be registered at all times put it in combat events.

Besides in classic short term events don't make sense for this mod anyways. that's done on retail because on retail we don't register tank warnings for someone above a certain level.

**Comment by venuatu** [comment]
@MysticalOS I swapped entangle into the high level check, seems like it wouldn't be an issue for higher levels

**Comment by QartemisT** [comment]
> @MysticalOS I swapped entangle into the high level check, seems like it wouldn't be an issue for higher levels

Looks okay 👍

**Pull request merged**
